//
// Generated file, do not edit! Created by nedtool 5.2 from src/priority.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PRIORITY_M_H
#define __PRIORITY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/priority.msg:3</tt> by nedtool.
 * <pre>
 * // Priority message from picocells to users
 * message PriorityMsg
 * {
 *     int source; // Picocell number
 *     int destination;    // User number
 *     int priority;
 * }
 * </pre>
 */
class PriorityMsg : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int priority;

  private:
    void copy(const PriorityMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PriorityMsg&);

  public:
    PriorityMsg(const char *name=nullptr, short kind=0);
    PriorityMsg(const PriorityMsg& other);
    virtual ~PriorityMsg();
    PriorityMsg& operator=(const PriorityMsg& other);
    virtual PriorityMsg *dup() const override {return new PriorityMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PriorityMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PriorityMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PRIORITY_M_H

